import { PrismaClient } from "@/generated/prisma"

const prisma = new PrismaClient()

async function main() {
  const result = await prisma.$executeRaw`INSERT INTO "PCard" ("filename", "name", "type", "plan", "rarity", "cost", "customCharacter") VALUES
    ("img_general_skillcard_acc-0_002", "眠気", "TROUBLE", "FREE", "T", null, false),
    ("img_general_skillcard_act-1_002", "軽い足取り", "ACTIVE", "SENSE", "R", "LOW", false),
    ("img_general_skillcard_act-1_019", "愛嬌", "ACTIVE", "SENSE", "R", "LOW", false),
    ("img_general_skillcard_act-1_022", "準備運動", "ACTIVE", "SENSE", "R", "LOW", true),
    ("img_general_skillcard_act-1_001", "ファンサ", "ACTIVE", "SENSE", "R", "LOW", false),
    ("img_general_skillcard_act-1_023", "勢い任せ", "ACTIVE", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_act-1_020", "ハイタッチ", "ACTIVE", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_act-1_021", "トークタイム", "ACTIVE", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_act-1_036", "エキサイト", "ACTIVE", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_act-1_027", "今日もおはよう", "ACTIVE", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_act-1_028", "ゆるふわおしゃべり", "ACTIVE", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_act-1_029", "もう少しだけ", "ACTIVE", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_act-1_003", "手拍子", "ACTIVE", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_act-1_004", "元気な挨拶", "ACTIVE", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_act-1_037", "デイドリーミング", "ACTIVE", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_act-1_038", "ジャストアピール", "ACTIVE", "ANOMALY", "R", "LOW", false),
    ("img_general_skillcard_act-1_040", "スターライト", "ACTIVE", "ANOMALY", "R", "LOW", false),
    ("img_general_skillcard_act-1_046", "一歩", "ACTIVE", "ANOMALY", "R", "LOW", false),
    ("img_general_skillcard_act-1_041", "ラッキー♪", "ACTIVE", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_act-1_042", "積み重ね", "ACTIVE", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_act-1_044", "精一杯", "ACTIVE", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_men-1_005", "気合十分！", "MENTAL", "FREE", "R", "HIGH", true),
    ("img_general_skillcard_men-1_007", "ファーストステップ", "MENTAL", "FREE", "R", "HIGH", false),
    ("img_general_skillcard_men-1_024", "バランス感覚", "MENTAL", "SENSE", "R", "LOW", false),
    ("img_general_skillcard_men-1_025", "楽観的", "MENTAL", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_men-1_008", "深呼吸", "MENTAL", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_men-1_034", "ひと呼吸", "MENTAL", "SENSE", "R", "HIGH", false),
    ("img_general_skillcard_men-1_030", "リスタート", "MENTAL", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_men-1_031", "えいえいおー", "MENTAL", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_men-1_006", "リズミカル", "MENTAL", "LOGIC", "R", "LOW", false),
    ("img_general_skillcard_men-1_032", "思い出し笑い", "MENTAL", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_men-1_033", "パステル気分", "MENTAL", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_men-1_009", "励まし", "MENTAL", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_men-1_035", "幸せのおまじない", "MENTAL", "LOGIC", "R", "HIGH", false),
    ("img_general_skillcard_men-1_039", "ハッピー♪", "MENTAL", "ANOMALY", "R", "LOW", false),
    ("img_general_skillcard_men-1_049", "嬉しい誤算", "MENTAL", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_men-1_048", "涙の思い出", "MENTAL", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_men-1_051", "セッティング", "MENTAL", "ANOMALY", "R", "HIGH", false),
    ("img_general_skillcard_act-2_009", "前途洋々", "ACTIVE", "FREE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_003", "決めポーズ", "ACTIVE", "SENSE", "SR", "LOW", true),
    ("img_general_skillcard_act-2_030", "アドリブ", "ACTIVE", "SENSE", "SR", "LOW", true),
    ("img_general_skillcard_act-2_031", "情熱ターン", "ACTIVE", "SENSE", "SR", "LOW", true),
    ("img_general_skillcard_act-2_033", "飛躍", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_042", "祝福", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_002", "スタートダッシュ", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_032", "スタンドプレー", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_001", "シュプレヒコール", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_059", "立ち位置チェック", "ACTIVE", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_046", "ラブリーウインク", "ACTIVE", "LOGIC", "SR", "LOW", true),
    ("img_general_skillcard_act-2_047", "ありがとうの言葉", "ACTIVE", "LOGIC", "SR", "LOW", true),
    ("img_general_skillcard_act-2_045", "ハートの合図", "ACTIVE", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_048", "キラメキ", "ACTIVE", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_049", "みんな大好き", "ACTIVE", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_062", "きらきら紙吹雪", "ACTIVE", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_065", "せーのっ！", "ACTIVE", "ANOMALY", "SR", "LOW", true),
    ("img_general_skillcard_act-2_072", "アッチェレランド", "ACTIVE", "ANOMALY", "SR", "LOW", true),
    ("img_general_skillcard_act-2_068", "はじけるパッション", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_069", "汗と成長", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_081", "第一印象", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_063", "オープニングアクト", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_070", "始まりの笑顔", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_082", "トレンドリーダー", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_067", "理想のテンポ", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_act-2_071", "トレーニングの成果", "ACTIVE", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_012", "アイドル宣言", "MENTAL", "FREE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_014", "ハイテンション", "MENTAL", "FREE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_039", "眼力", "MENTAL", "SENSE", "SR", "LOW", true),
    ("img_general_skillcard_men-2_043", "大声援", "MENTAL", "SENSE", "SR", "LOW", true),
    ("img_general_skillcard_men-2_034", "演出計画", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_038", "願いの力", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_035", "静かな意志", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_036", "始まりの合図", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_040", "意地", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_037", "存在感", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_041", "成功への道筋", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_011", "スポットライト", "MENTAL", "SENSE", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_053", "あふれる思い出", "MENTAL", "LOGIC", "SR", "LOW", true),
    ("img_general_skillcard_men-2_055", "ふれあい", "MENTAL", "LOGIC", "SR", "LOW", true),
    ("img_general_skillcard_men-2_050", "幸せな時間", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_058", "ファンシーチャーム", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_004", "ワクワクが止まらない", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_054", "本番前夜", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_052", "ひなたぼっこ", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_008", "イメトレ", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_051", "やる気は満点", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_057", "ゆめみごこち", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_056", "止められない想い", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_060", "オトメゴコロ", "MENTAL", "LOGIC", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_064", "潜在能力", "MENTAL", "ANOMALY", "SR", "LOW", true),
    ("img_general_skillcard_act-2_073", "カウントダウン", "MENTAL", "ANOMALY", "SR", "LOW", true),
    ("img_general_skillcard_men-2_075", "モチベ", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_066", "プライド", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_076", "盛り上げ上手", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_080", "インフルエンサー", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_077", "忍耐力", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_079", "切磋琢磨", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_men-2_074", "タフネス", "MENTAL", "ANOMALY", "SR", "HIGH", true),
    ("img_general_skillcard_sup-2_025", "お姉ちゃんだもの！", "ACTIVE", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_026", "おアツイ視線", "MENTAL", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_027", "ご指導ご鞭撻", "ACTIVE", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_028", "ストレッチ談義", "ACTIVE", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_029", "全力サポート", "MENTAL", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_092", "旬の味わい", "ACTIVE", "FREE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_087", "キメ顔で自撮り", "MENTAL", "SENSE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_088", "切れた鼻緒が結んだ絆", "MENTAL", "SENSE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_090", "気になる……", "MENTAL", "SENSE", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_086", "なに聴いてるの？", "ACTIVE", "LOGIC", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_091", "こうかい……？", "ACTIVE", "LOGIC", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_094", "ディテールが肝心", "ACTIVE", "LOGIC", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_095", "草笛ハーモニー", "MENTAL", "LOGIC", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_093", "愛情レインボー", "MENTAL", "ANOMALY", "SUPPORT", null, false),
    ("img_general_skillcard_sup-2_096", "小さなお客さん", "ACTIVE", "ANOMALY", "SUPPORT", null, false)`
  console.log(result)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
